import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Waymark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button variant="contained">Hello World</Button>
    </div>
  )
}

export default Home
